### ISSUE TITLE
There is no longer Flask Celery support

### ISSUE THREAD

**Issue by JhossePaul** [Robpol86/Flask-Large-Application-Example#5]
It could be great to update Celery support because since Celery 3+ extension is not needed.

http://flask.pocoo.org/docs/0.11/patterns/celery/
https://github.com/ask/flask-celery

**Comment by Robpol86** [comment]
Nothing has changed since I wrote this app. I found that I still needed a Celery Flask extension because of Flask app config values needing to be passed to Celery after instantiating.

It's been a while so I forgot the details but I needed an extension to use with the factory approach in large Flask applications.

**Comment by Robpol86** [comment]
More info in the readme: https://github.com/Robpol86/Flask-Celery-Helper
